version: '2'
services:
  mysql:
    container_name: quiz_mysql_prd
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "3306"
    volumes:
      - /mnt/efs/quiz_mysql:/var/lib/mysql
  app:
    container_name: quiz_app_prd
    image: ${DOCKER_IMAGE}
    ports:
      - "80"
    environment:
      DATABASE_URI: '${DATABASE_URI}'
    command: /run.sh
    labels:
      traefik.frontend.rule: "${CONTAINER_HOSTS}"
      traefik.backend.loadbalancer.method: "drr"
      traefik.frontend.entryPoints: "http,https"
    links:
      - mysql:mysql
      - mysql:db
